/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author MOHAMED FATHEEM
 */
public class AfterLogin extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. 
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet AfterLogin</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet AfterLogin at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");*/

            out.println("<!DOCTYPE html>\n"
                    + "<!--\n"
                    + "To change this license header, choose License Headers in Project Properties.\n"
                    + "To change this template file, choose Tools | Templates\n"
                    + "and open the template in the editor.\n"
                    + "-->\n"
                    + "<!DOCTYPE html>\n"
                    + "<html >\n"
                    + "<head>\n"
                    + "\n"
                    + "  <meta charset=\"UTF-8\">\n"
                    + "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                    + "\n"
                    + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1\">\n"
                    + "  <link rel=\"shortcut icon\" href=\"assets/images/download-122x122.png\" type=\"image/x-icon\">\n"
                    + "  <meta name=\"description\" content=\"\">\n"
                    + "  <title>Home</title>\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/web/assets/mobirise-icons/mobirise-icons.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/tether/tether.min.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap-grid.min.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap-reboot.min.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/animatecss/animate.min.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/socicon/css/styles.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/dropdown/css/style.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/theme/css/style.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/gallery/style.css\">\n"
                    + "  <link rel=\"stylesheet\" href=\"assets/mobirise/css/mbr-additional.css\" type=\"text/css\">\n"
                    + "  \n"
                    + "  \n"
                    + "  \n"
                    + "</head>\n"
                    + "<body>\n"
                    + "  <section class=\"menu cid-qNj6ntBtz6\" once=\"menu\" id=\"menu1-1n\">\n"
                    + "\n"
                    + "    \n"
                    + "\n"
                    + "    <nav class=\"navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm bg-color transparent\">\n"
                    + "        <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
                    + "            <div class=\"hamburger\">\n"
                    + "                <span></span>\n"
                    + "                <span></span>\n"
                    + "                <span></span>\n"
                    + "                <span></span>\n"
                    + "            </div>\n"
                    + "        </button>\n"
                    + "        <div class=\"menu-logo\">\n"
                    + "            <div class=\"navbar-brand\">\n"
                    + "                <span class=\"navbar-logo\">\n"
                    + "                    <a href=\"#\">\n"
                    + "                         <img src=\"assets/images/download-122x122.png\" title=\"\" style=\"height: 3.8rem;\">\n"
                    + "                    </a>\n"
                    + "                </span>\n"
                    + "                <span class=\"navbar-caption-wrap\"><a class=\"navbar-caption text-white display-4\" href=\"#\">IP</a></span>\n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
                    + "            <ul class=\"navbar-nav nav-dropdown\" data-app-modern-menu=\"true\"><li class=\"nav-item\"><a class=\"nav-link link text-white display-4\" href=# aria-expanded=\"true\"></a></li><li class=\"nav-item\">\n"
                    + "                   <!-- <a class=\"nav-link link text-white display-4\" href=#>\n"
                    + "                        <span class=\"mbri-search mbr-iconfont mbr-iconfont-btn\"></span>\n"
                    + "                        About Us\n"
                    + "                    </a>-->\n"
                    + "                </li><li class=\"nav-item dropdown open\">\n"
                    + "                    <a class=\"nav-link link dropdown-toggle text-white display-4\" href=# data-toggle=\"dropdown-submenu\" aria-expanded=\"true\">\n"
                    + "                        <span class=\"mbri-home mbr-iconfont mbr-iconfont-btn\"></span>\n"
                    + "                        Services\n"
                    + "                    </a><div class=\"dropdown-menu\"><div class=\"dropdown\"><a class=\"dropdown-item dropdown-toggle text-white display-4\" href=# data-toggle=\"dropdown-submenu\" aria-expanded=\"false\">CSC<br></a><div class=\"dropdown-menu dropdown-submenu\"><a class=\"dropdown-item text-white display-4\" href=\"csc.html#testimonials1-e\">Agriculture<br></a><a class=\"dropdown-item text-white display-4\" href=\"csc.html#testimonials1-e\" aria-expanded=\"false\">Financial Inclusion</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">Education</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">Digipay</a><a class=\"dropdown-item text-white display-4\" href=\"csc.html#testimonials1-e\" aria-expanded=\"false\">Government to Citizen</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">Health Services</a><a class=\"dropdown-item text-white display-4\" href=\"csc.html#info1-f\" aria-expanded=\"false\">Digitize India platform</a></div></div><div class=\"dropdown\"><a class=\"dropdown-item text-white dropdown-toggle display-4\" href=# aria-expanded=\"false\" data-toggle=\"dropdown-submenu\">CSR</a><div class=\"dropdown-menu dropdown-submenu\"><a class=\"dropdown-item text-white display-4\" href=\"csr.html#features2-b\" aria-expanded=\"false\">Environmental sustainability</a><a class=\"dropdown-item text-white display-4\" href=\"csr.html#features2-b\" aria-expanded=\"false\">Ethical marketing</a><a class=\"dropdown-item text-white display-4\" href=\"csr.html#features2-b\" aria-expanded=\"false\">Triple bottom line</a><a class=\"dropdown-item text-white display-4\" href=\"csr.html#table1-l\" aria-expanded=\"false\">CSR Sponsership</a></div></div><a class=\"dropdown-item text-white display-4\" href=\"isa.html#content11-7\" aria-expanded=\"true\">ISA</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">NIF</a><div class=\"dropdown open\"><a class=\"dropdown-item text-white dropdown-toggle display-4\" href=# aria-expanded=\"true\" data-toggle=\"dropdown-submenu\">CSIR</a><div class=\"dropdown-menu dropdown-submenu\"><a class=\"dropdown-item text-white display-4\" href=\"csir.html#features17-1e\" aria-expanded=\"false\">Biological Sciences</a><a class=\"dropdown-item text-white display-4\" href=\"csir.html#features17-1e\" aria-expanded=\"false\">Chemical Sciences</a><a class=\"dropdown-item text-white display-4\" href=\"csir.html#features17-1e\" aria-expanded=\"false\">Engineering Sciences</a><a class=\"dropdown-item text-white display-4\" href=\"csir.html#features17-1e\" aria-expanded=\"false\">Physical Sciences</a><a class=\"dropdown-item text-white display-4\" href=\"csir.html#features17-1e\" aria-expanded=\"false\">Information Sciences</a><a class=\"dropdown-item text-white display-4\" href=\"csir.html#features17-1e\" aria-expanded=\"false\">CSIR 800</a></div></div><div class=\"dropdown\"><a class=\"dropdown-item text-white dropdown-toggle display-4\" href=# aria-expanded=\"false\" data-toggle=\"dropdown-submenu\">DIGITAL INDIA</a><div class=\"dropdown-menu dropdown-submenu\"><a class=\"dropdown-item text-white display-4\" href=\"digitalindia.html#testimonials1-19\" aria-expanded=\"false\">Startup India</a><a class=\"dropdown-item text-white display-4\" href=\"digitalindia.html#testimonials1-19\" aria-expanded=\"false\">Passport Seva</a><a class=\"dropdown-item text-white display-4\" href=\"digitalindia.html#testimonials1-19\" aria-expanded=\"false\">Election Commission Of India</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">BHIM</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">e-Visa</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">Kisan Suvidha</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\"></a></div></div><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">SWACHH BHARATH</a><div class=\"dropdown\"><a class=\"dropdown-item text-white dropdown-toggle display-4\" href=# aria-expanded=\"false\" data-toggle=\"dropdown-submenu\">MAKE IN INDIA<br></a><div class=\"dropdown-menu dropdown-submenu\"><a class=\"dropdown-item text-white display-4\" href=\"min.html#testimonials1-8\" aria-expanded=\"false\">Digital India</a><a class=\"dropdown-item text-white display-4\" href=\"min.html#testimonials1-8\" aria-expanded=\"false\">Startup India</a><a class=\"dropdown-item text-white display-4\" href=\"min.html#testimonials1-8\" aria-expanded=\"false\">Skill India</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">AMRUT</a><a class=\"dropdown-item text-white display-4\" href=# aria-expanded=\"false\">Smart City</a></div></div></div>\n"
                    + "                </li><li class=\"nav-item dropdown\"><a class=\"nav-link link text-white dropdown-toggle display-4\" href=# aria-expanded=\"false\" data-toggle=\"dropdown-submenu\"><span class=\"mbri-clock mbr-iconfont mbr-iconfont-btn\"></span>Events</a><div class=\"dropdown-menu\"><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"false\">Upcoming events</a><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"false\">Past events</a></div></li><li class=\"nav-item dropdown\"><a class=\"nav-link link text-white dropdown-toggle display-4\" href=# aria-expanded=\"false\" data-toggle=\"dropdown-submenu\"><span class=\"mbri-star mbr-iconfont mbr-iconfont-btn\"></span>Awards&nbsp;</a><div class=\"dropdown-menu\"><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"false\">Swachh Bharat</a><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"false\">CSIR</a></div></li><li class=\"nav-item dropdown\"><a class=\"nav-link link text-white dropdown-toggle display-4\" href=\"/Ideas\" aria-expanded=\"false\" data-toggle=\"dropdown-submenu\"><span class=\"mbri-idea mbr-iconfont mbr-iconfont-btn\"></span>Ideas</a><div class=\"dropdown-menu\"><div class=\"dropdown\"><a class=\"text-white dropdown-item dropdown-toggle display-4\" href=# aria-expanded=\"false\" data-toggle=\"dropdown-submenu\">NIF</a><div class=\"dropdown-menu dropdown-submenu\"><a class=\"text-white dropdown-item display-4\" href=\"UserSubmitIdeas.jsp\" aria-expanded=\"false\">Submit Idea</a></div></div><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"true\">CSR</a><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"true\">CSIR</a><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"true\">CSC</a><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"true\">ISA</a><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"true\">Digital India</a><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"true\">Swachh Bharat</a><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"true\">Make In India</a><a class=\"text-white dropdown-item display-4\" href=# aria-expanded=\"true\"></a></div></li><li class=\"nav-item\"><a class=\"nav-link link text-white display-4\" href=# aria-expanded=\"false\">\n"
                    + "                        </a></li><li class=\"nav-item\"><a class=\"nav-link link text-white display-4\" href=#>\n"
                    + "                        </a></li></ul>\n"
                    + "            <div class=\"navbar-buttons mbr-section-btn\"><a class=\"btn btn-sm btn-white-outline display-4\" href=\"Logout.jsp\">\n"
                    + "                    <font face=\"MobiriseIcons\"><span style=\"font-size: 25.6px;\">Logout</span></font></a></div>\n"
                    + "        </div>\n"
                    + "    </nav>\n"
                    + "</section>\n"
                    + "\n"
                    + "<section class=\"cid-qM3QV7rh7J mbr-fullscreen mbr-parallax-background\" id=\"header2-i\">\n"
                    + "\n"
                    + "    \n"
                    + "\n"
                    + "    <div class=\"mbr-overlay\" style=\"opacity: 0.5; background-color: rgb(118, 118, 118);\"></div>\n"
                    + "\n"
                    + "    <div class=\"container align-center\">\n"
                    + "        <div class=\"row justify-content-md-center\">\n"
                    + "            <div class=\"mbr-white col-md-10\">\n"
                    + "                <h1 class=\"mbr-section-title mbr-bold pb-3 mbr-fonts-style display-1\">INNERPRENEUR</h1>\n"
                    + "                \n"
                    + "                <p class=\"mbr-text pb-3 mbr-fonts-style display-2\">This is an integrated websites for all government organisations</p>\n"
                    + "                \n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "    <div class=\"mbr-arrow hidden-sm-down\" aria-hidden=\"true\">\n"
                    + "        <a href=\"#next\">\n"
                    + "            <i class=\"mbri-down mbr-iconfont\"></i>\n"
                    + "        </a>\n"
                    + "    </div>\n"
                    + "</section>\n"
                    + "\n"
                    + "<section class=\"mbr-gallery mbr-slider-carousel cid-qMz3M2lAVm\" id=\"gallery1-1i\">\n"
                    + "\n"
                    + "    \n"
                    + "\n"
                    + "    <div class=\"container\">\n"
                    + "        <div><!-- Filter --><!-- Gallery --><div class=\"mbr-gallery-row\"><div class=\"mbr-gallery-layout-default\"><div><div><div class=\"mbr-gallery-item mbr-gallery-item--p1\" data-video-url=\"false\" data-tags=\"Awesome\"><div href=\"#lb-gallery1-1i\" data-slide-to=\"0\" data-toggle=\"modal\"><img src=\"assets/images/1-1620x1080-800x533.jpg\" alt=\"\"><span class=\"icon-focus\"></span><span class=\"mbr-gallery-title mbr-fonts-style display-7\">Founding Conference of ISA</span></div></div><div class=\"mbr-gallery-item mbr-gallery-item--p1\" data-video-url=\"false\" data-tags=\"Responsive\"><div href=\"#lb-gallery1-1i\" data-slide-to=\"1\" data-toggle=\"modal\"><img src=\"assets/images/9thaward3-800x534-800x534.jpg\" alt=\"\"><span class=\"icon-focus\"></span><span class=\"mbr-gallery-title mbr-fonts-style display-7\">9th National Grassroots Innovation and Award function</span></div></div><div class=\"mbr-gallery-item mbr-gallery-item--p1\" data-video-url=\"false\" data-tags=\"Creative\"><div href=\"#lb-gallery1-1i\" data-slide-to=\"2\" data-toggle=\"modal\"><img src=\"assets/images/make-in-india-launch-8-800x400-261x172.jpg\" alt=\"\"><span class=\"icon-focus\"></span><span class=\"mbr-gallery-title mbr-fonts-style display-7\">Prime Minister Narendra Modi, delegates from 56 countries and several other dignitaries took part in the conference&nbsp;</span></div></div><div class=\"mbr-gallery-item mbr-gallery-item--p1\" data-video-url=\"false\" data-tags=\"Animated\"><div href=\"#lb-gallery1-1i\" data-slide-to=\"3\" data-toggle=\"modal\"><img src=\"assets/images/img-20170918-131439203-640x340-451x297.jpg\" alt=\"\"><span class=\"icon-focus\"></span><span class=\"mbr-gallery-title mbr-fonts-style display-7\">India CSR summit 2017</span></div></div><div class=\"mbr-gallery-item mbr-gallery-item--p1\" data-video-url=\"false\" data-tags=\"Awesome\"><div href=\"#lb-gallery1-1i\" data-slide-to=\"4\" data-toggle=\"modal\"><img src=\"assets/images/prime-minister-narendra-modi-at-the-stage-for-digital-india-dinner-6-1024x543-790x539.jpg\" alt=\"\"><span class=\"icon-focus\"></span><span class=\"mbr-gallery-title mbr-fonts-style display-7\">Digital India conference</span></div></div><div class=\"mbr-gallery-item mbr-gallery-item--p1\" data-video-url=\"false\" data-tags=\"Awesome\"><div href=\"#lb-gallery1-1i\" data-slide-to=\"5\" data-toggle=\"modal\"><img src=\"assets/images/pm-modi-2-1156x548-800x516.jpg\" alt=\"\"><span class=\"icon-focus\"></span><span class=\"mbr-gallery-title mbr-fonts-style display-7\">CSIR PLATINUM JUBILEE</span></div></div><div class=\"mbr-gallery-item mbr-gallery-item--p1\" data-video-url=\"false\" data-tags=\"Responsive\"><div href=\"#lb-gallery1-1i\" data-slide-to=\"6\" data-toggle=\"modal\"><img src=\"assets/images/s20170822112332-4-500x308-385x269.jpg\" alt=\"\"><span class=\"icon-focus\"></span><span class=\"mbr-gallery-title mbr-fonts-style display-7\">National Cinference on Emergency opportunity through CSC</span></div></div><div class=\"mbr-gallery-item mbr-gallery-item--p1\" data-video-url=\"false\" data-tags=\"Animated\"><div href=\"#lb-gallery1-1i\" data-slide-to=\"7\" data-toggle=\"modal\"><img src=\"assets/images/slider-16-3-18-2-1130x420-626x417.jpg\" alt=\"\"><span class=\"icon-focus\"></span><span class=\"mbr-gallery-title mbr-fonts-style display-7\">Festival Of Innovation and Entrepreneurship</span></div></div></div></div><div class=\"clearfix\"></div></div></div><!-- Lightbox --><div data-app-prevent-settings=\"\" class=\"mbr-slider modal fade carousel slide\" tabindex=\"-1\" data-keyboard=\"true\" data-interval=\"false\" id=\"lb-gallery1-1i\"><div class=\"modal-dialog\"><div class=\"modal-content\"><div class=\"modal-body\"><div class=\"carousel-inner\"><div class=\"carousel-item\"><img src=\"assets/images/1-1620x1080.jpg\" alt=\"\"></div><div class=\"carousel-item\"><img src=\"assets/images/9thaward3-800x534.jpg\" alt=\"\"></div><div class=\"carousel-item\"><img src=\"assets/images/make-in-india-launch-8-800x400.jpg\" alt=\"\"></div><div class=\"carousel-item\"><img src=\"assets/images/img-20170918-131439203-640x340.jpg\" alt=\"\"></div><div class=\"carousel-item\"><img src=\"assets/images/prime-minister-narendra-modi-at-the-stage-for-digital-india-dinner-6-1024x543.jpg\" alt=\"\"></div><div class=\"carousel-item active\"><img src=\"assets/images/pm-modi-2-1156x548.jpg\" alt=\"\"></div><div class=\"carousel-item\"><img src=\"assets/images/s20170822112332-4-500x308.jpg\" alt=\"\"></div><div class=\"carousel-item\"><img src=\"assets/images/slider-16-3-18-2-1130x420.jpg\" alt=\"\"></div></div><a class=\"carousel-control carousel-control-prev\" role=\"button\" data-slide=\"prev\" href=\"#lb-gallery1-1i\"><span class=\"mbri-left mbr-iconfont\" aria-hidden=\"true\"></span><span class=\"sr-only\">Previous</span></a><a class=\"carousel-control carousel-control-next\" role=\"button\" data-slide=\"next\" href=\"#lb-gallery1-1i\"><span class=\"mbri-right mbr-iconfont\" aria-hidden=\"true\"></span><span class=\"sr-only\">Next</span></a><a class=\"close\" href=\"\"#\" role=\"button\" data-dismiss=\"modal\"><span class=\"sr-only\">Close</span></a></div></div></div></div></div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "</section>\n"
                    + "\n"
                    + "<section class=\"features16 cid-qMqT8zdUlt\" id=\"features16-18\">\n"
                    + "    \n"
                    + "    \n"
                    + "    \n"
                    + "    <div class=\"container align-center\">\n"
                    + "        <h2 class=\"pb-3 mbr-fonts-style mbr-section-title display-2\">\n"
                    + "            OUR CLIENT ORGANISATIONS</h2>\n"
                    + "        \n"
                    + "        <div class=\"row media-row\">\n"
                    + "            \n"
                    + "        <div class=\"team-item col-lg-3 col-md-6\">\n"
                    + "                <div class=\"item-image\">\n"
                    + "                    <a href=\"csc.html\"><img src=\"assets/images/oie-transparent-14-510x510.png\" alt=\"\" title=\"\"></a>\n"
                    + "                </div>\n"
                    + "                <div class=\"item-caption py-3\">\n"
                    + "                    <div class=\"item-name px-2\">\n"
                    + "                        <a href=\"csc.html\"><p class=\"mbr-fonts-style display-5\">CSC</p></a>\n"
                    + "                    </div>\n"
                    + "                    \n"
                    + "                    \n"
                    + "                </div>\n"
                    + "            </div><div class=\"team-item col-lg-3 col-md-6\">\n"
                    + "                <div class=\"item-image\">\n"
                    + "                    <a href=\"csir.html\"><img src=\"assets/images/oie-transparent-13-510x510.png\" alt=\"\" title=\"\"></a>\n"
                    + "                </div>\n"
                    + "                <div class=\"item-caption py-3\">\n"
                    + "                    <div class=\"item-name px-2\">\n"
                    + "                        <a href=\"csir.html\"><p class=\"mbr-fonts-style display-5\">CSIR</p></a>\n"
                    + "                    </div>\n"
                    + "                    \n"
                    + "                    \n"
                    + "                </div>\n"
                    + "            </div><div class=\"team-item col-lg-3 col-md-6\">\n"
                    + "                <div class=\"item-image\">\n"
                    + "                    <a href=\"min.html\"><img src=\"assets/images/oie-transparent-3-510x510.png\" alt=\"\" title=\"\"></a>\n"
                    + "                </div>\n"
                    + "                <div class=\"item-caption py-3\">\n"
                    + "                    <div class=\"item-name px-2\">\n"
                    + "                       <a href=\"min.html\"> <p class=\"mbr-fonts-style display-5\">MAKE IN INDIA</p></a>\n"
                    + "                    </div>\n"
                    + "                    \n"
                    + "                    \n"
                    + "                </div>\n"
                    + "            </div><div class=\"team-item col-lg-3 col-md-6\">\n"
                    + "                <div class=\"item-image\">\n"
                    + "                   <a href=\"isa.html\"> <img src=\"assets/images/oie-transparent-6-510x510.png\" alt=\"\" title=\"\"></a>\n"
                    + "                </div>\n"
                    + "                <div class=\"item-caption py-3\">\n"
                    + "                    <div class=\"item-name px-2\">\n"
                    + "                        <a href=\"isa.html\"><p class=\"mbr-fonts-style display-5\">ISA</p></a>\n"
                    + "                    </div>\n"
                    + "                    \n"
                    + "                    \n"
                    + "                </div>\n"
                    + "            </div></div>    \n"
                    + "    </div>\n"
                    + "</section>\n"
                    + "\n"
                    + "<section class=\"features16 cid-qMrdbiuq0P\" id=\"features16-1e\">\n"
                    + "    \n"
                    + "    \n"
                    + "    \n"
                    + "    <div class=\"container align-center\">\n"
                    + "        \n"
                    + "        \n"
                    + "        <div class=\"row media-row\">\n"
                    + "            \n"
                    + "        <div class=\"team-item col-lg-3 col-md-6\">\n"
                    + "                <div class=\"item-image\">\n"
                    + "                    <a href=\"digitalindia.html\"><img src=\"assets/images/oie-transparent-7-510x510.png\" alt=\"\" title=\"\"></a>\n"
                    + "                </div>\n"
                    + "                <div class=\"item-caption py-3\">\n"
                    + "                    <div class=\"item-name px-2\">\n"
                    + "                        <a href=\"digitalindia.html\"><p class=\"mbr-fonts-style display-5\">DIGITAL INDIA</p></a>\n"
                    + "                    </div>\n"
                    + "                    \n"
                    + "                    \n"
                    + "                </div>\n"
                    + "            </div><div class=\"team-item col-lg-3 col-md-6\">\n"
                    + "                <div class=\"item-image\">\n"
                    + "                    <a href=\"swachh.html\"><img src=\"assets/images/oie-transparent-12-510x510.png\" alt=\"\" title=\"\"></a>\n"
                    + "                </div>\n"
                    + "                <div class=\"item-caption py-3\">\n"
                    + "                    <div class=\"item-name px-2\">\n"
                    + "                        <a href=\"swachh.html\"><p class=\"mbr-fonts-style display-5\">SWACHH BHARAT</p></a>\n"
                    + "                    </div>\n"
                    + "                    \n"
                    + "                    \n"
                    + "                </div>\n"
                    + "            </div><div class=\"team-item col-lg-3 col-md-6\">\n"
                    + "                <div class=\"item-image\">\n"
                    + "                    <a href=\"nif.html\"><img src=\"assets/images/oie-transparent-10-510x510.png\" alt=\"\" title=\"\"></a>\n"
                    + "                </div>\n"
                    + "                <div class=\"item-caption py-3\">\n"
                    + "                    <div class=\"item-name px-2\">\n"
                    + "                        <a href=\"nif.html\"><p class=\"mbr-fonts-style display-5\">NIF</p></a>\n"
                    + "                    </div>\n"
                    + "                    \n"
                    + "                    \n"
                    + "                </div>\n"
                    + "            </div><div class=\"team-item col-lg-3 col-md-6\">\n"
                    + "                <div class=\"item-image\">\n"
                    + "                    <a href=\"csr.html\"><img src=\"assets/images/oie-transparent-11-510x510.png\" alt=\"\" title=\"\"></a>\n"
                    + "                </div>\n"
                    + "                <div class=\"item-caption py-3\">\n"
                    + "                    <div class=\"item-name px-2\">\n"
                    + "                       <a href=\"csr.html\"> <p class=\"mbr-fonts-style display-5\">CSR</p></a>\n"
                    + "                    </div>\n"
                    + "                    \n"
                    + "                    \n"
                    + "                </div>\n"
                    + "            </div></div>    \n"
                    + "    </div>\n"
                    + "</section>\n"
                    + "\n"
                    + "<section class=\"clients cid-qMlsPM6Fs0\" id=\"clients-17\">\n"
                    + "      \n"
                    + "\n"
                    + "    \n"
                    + "        \n"
                    + "\n"
                    + "    <div class=\"container\">\n"
                    + "        <div class=\"carousel slide\" data-ride=\"carousel\" role=\"listbox\">\n"
                    + "            <div class=\"carousel-inner\" data-visible=\"6\">\n"
                    + "                \n"
                    + "                \n"
                    + "                \n"
                    + "                \n"
                    + "                \n"
                    + "            <div class=\"carousel-item \">\n"
                    + "                    <div class=\"media-container-row\">\n"
                    + "                        <div class=\"col-md-12\">\n"
                    + "                            <div class=\"wrap-img \">\n"
                    + "                                <img src=\"assets/images/oie-transparent-3-182x88.png\" class=\"img-responsive clients-img\" alt=\"\" title=\"\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div><div class=\"carousel-item \">\n"
                    + "                    <div class=\"media-container-row\">\n"
                    + "                        <div class=\"col-md-12\">\n"
                    + "                            <div class=\"wrap-img \">\n"
                    + "                                <img src=\"assets/images/oie-transparent-4-198x73.png\" class=\"img-responsive clients-img\" alt=\"\" title=\"\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div><div class=\"carousel-item \">\n"
                    + "                    <div class=\"media-container-row\">\n"
                    + "                        <div class=\"col-md-12\">\n"
                    + "                            <div class=\"wrap-img \">\n"
                    + "                                <img src=\"assets/images/swach-bharat-abhiyan-d-234x102.png\" class=\"img-responsive clients-img\" alt=\"\" title=\"\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div><div class=\"carousel-item \">\n"
                    + "                    <div class=\"media-container-row\">\n"
                    + "                        <div class=\"col-md-12\">\n"
                    + "                            <div class=\"wrap-img \">\n"
                    + "                                <img src=\"assets/images/make-in-india-d-190x90.jpg\" class=\"img-responsive clients-img\" alt=\"\" title=\"\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div><div class=\"carousel-item \">\n"
                    + "                    <div class=\"media-container-row\">\n"
                    + "                        <div class=\"col-md-12\">\n"
                    + "                            <div class=\"wrap-img \">\n"
                    + "                                <img src=\"assets/images/oie-16544489oxyiysi-1-118x116.png\" class=\"img-responsive clients-img\" alt=\"\" title=\"\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div><div class=\"carousel-item \">\n"
                    + "                    <div class=\"media-container-row\">\n"
                    + "                        <div class=\"col-md-12\">\n"
                    + "                            <div class=\"wrap-img \">\n"
                    + "                                <img src=\"assets/images/digital-india-d-249x140.png\" class=\"img-responsive clients-img\" alt=\"\" title=\"\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div><div class=\"carousel-item \">\n"
                    + "                    <div class=\"media-container-row\">\n"
                    + "                        <div class=\"col-md-12\">\n"
                    + "                            <div class=\"wrap-img \">\n"
                    + "                                <img src=\"assets/images/csr-01-edited-273x102.png\" class=\"img-responsive clients-img\" alt=\"\" title=\"\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div><div class=\"carousel-item \">\n"
                    + "                    <div class=\"media-container-row\">\n"
                    + "                        <div class=\"col-md-12\">\n"
                    + "                            <div class=\"wrap-img \">\n"
                    + "                                <img src=\"assets/images/oie-transparent-15-123x101.png\" class=\"img-responsive clients-img\" alt=\"\" title=\"\">\n"
                    + "                            </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div></div>\n"
                    + "            <div class=\"carousel-controls\">\n"
                    + "                <a data-app-prevent-settings=\"\" class=\"carousel-control carousel-control-prev\" role=\"button\" data-slide=\"prev\">\n"
                    + "                    <span aria-hidden=\"true\" class=\"mbri-left mbr-iconfont\"></span>\n"
                    + "                    <span class=\"sr-only\">Previous</span>\n"
                    + "                </a>\n"
                    + "                <a data-app-prevent-settings=\"\" class=\"carousel-control carousel-control-next\" role=\"button\" data-slide=\"next\">\n"
                    + "                    <span aria-hidden=\"true\" class=\"mbri-right mbr-iconfont\"></span>\n"
                    + "                    <span class=\"sr-only\">Next</span>\n"
                    + "                </a>\n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "</section>\n"
                    + "\n"
                    + "<section class=\"footer3 cid-qMgfDAA7xx mbr-reveal\" id=\"footer3-11\">\n"
                    + "\n"
                    + "    \n"
                    + "\n"
                    + "    \n"
                    + "\n"
                    + "    <div class=\"container\">\n"
                    + "        <div class=\"media-container-row content\">\n"
                    + "            <div class=\"col-md-2 col-sm-4\">\n"
                    + "                <div class=\"mb-3 img-logo\">\n"
                    + "                    <a href=#/\">\n"
                    + "                         <img src=\"assets/images/download-192x192.png\" alt=\"Mobirise\" title=\"\">\n"
                    + "                    </a>\n"
                    + "                </div>\n"
                    + "                <p class=\"mbr-fonts-style foot-logo display-5\">INNERPRENEUR</p>\n"
                    + "            </div>\n"
                    + "            <div class=\"col-md-3 col-sm-4\">\n"
                    + "                <p class=\"mb-4 mbr-fonts-style foot-title display-7\"></p>\n"
                    + "                <p class=\"mbr-text mbr-links-column mbr-fonts-style display-7\">\n"
                    + "                    <a href=\"\"#\" class=\"text-black\">About us</a>\n"
                    + "                    <br><a href=\"\"#\" class=\"text-black\">Services</a>\n"
                    + "                    <br>Privacy Policy<br>Terms&amp;Conditions</p>\n"
                    + "            </div>\n"
                    + "            <div class=\"col-md-3 col-sm-4\">\n"
                    + "                <p class=\"mb-4 mbr-fonts-style foot-title display-7\"></p>\n"
                    + "                <p class=\"mbr-text mbr-fonts-style mbr-links-column display-7\">Contact Us<br>Feedback<br>Blogs<br><a href=\"\"#\" class=\"text-black\">S</a>ign Up<br><br></p>\n"
                    + "            </div>\n"
                    + "            <div class=\"col-md-4 col-sm-12\">\n"
                    + "                    \n"
                    + "\n"
                    + "                   <!-- <form class=\"form-inline\" action=#/\" method=\"post\" data-form-title=\"Mobirise Form\">\n"
                    + "                        <input type=\"hidden\" value=\"6MHWjg/n/NFwyu6fXkLJLtlLLFda5aCMbHJVwyJfbutfC1FJPsfjSQqJSoWR76cz9eTdH1H0SAqRINTcn1Gv/2ukmUEq/7Y0Hd3Q4yLBxp2BCPM1+b8QXr5vthgCOfbk\" data-form-email=\"true\">\n"
                    + "                        <div class=\"form-group\">\n"
                    + "                            <input type=\"email\" class=\"form-control input-sm input-inverse my-2\" name=\"email\" required=\"\" data-form-field=\"Email\" placeholder=\"Email\" id=\"email-footer3-11\">\n"
                    + "                        </div>\n"
                    + "                        <div class=\"input-group-btn m-2\">\n"
                    + "                            <button href=\"\" class=\"btn btn-primary display-4\" type=\"submit\" role=\"button\">Subscribe</button>\n"
                    + "                        </div>\n"
                    + "                    </form>-->\n"
                    + "                </div>\n"
                    + "\n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "        <div class=\"footer-lower\">\n"
                    + "            <div class=\"media-container-row\">\n"
                    + "                <div class=\"col-sm-12\">\n"
                    + "                    <hr>\n"
                    + "                </div>\n"
                    + "            </div>\n"
                    + "            <div class=\"media-container-row\">\n"
                    + "                <div class=\"col-sm-6 copyright\">\n"
                    + "                    <p class=\"mbr-text mbr-fonts-style display-7\">\n"
                    + "                        © Copyright 2018 SPE - All Rights Reserved\n"
                    + "                    </p>\n"
                    + "                </div>\n"
                    + "                <div class=\"col-md-6\">\n"
                    + "                    <div class=\"social-list align-right\">\n"
                    + "                        <div class=\"soc-item\">\n"
                    + "                            <a href=\"https://twitter.com/mobirise\" target=\"_blank\">\n"
                    + "                                <span class=\"socicon-twitter socicon mbr-iconfont mbr-iconfont-social\"></span>\n"
                    + "                            </a>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"soc-item\">\n"
                    + "                            <a href=\"https://www.facebook.com/pages/Mobirise/1616226671953247\" target=\"_blank\">\n"
                    + "                                <span class=\"socicon-facebook socicon mbr-iconfont mbr-iconfont-social\"></span>\n"
                    + "                            </a>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"soc-item\">\n"
                    + "                            <a href=\"https://www.youtube.com/c/mobirise\" target=\"_blank\">\n"
                    + "                                <span class=\"socicon-youtube socicon mbr-iconfont mbr-iconfont-social\"></span>\n"
                    + "                            </a>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"soc-item\">\n"
                    + "                            <a href=\"https://instagram.com/mobirise\" target=\"_blank\">\n"
                    + "                                <span class=\"socicon-instagram socicon mbr-iconfont mbr-iconfont-social\"></span>\n"
                    + "                            </a>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"soc-item\">\n"
                    + "                            <a href=\"https://plus.google.com/u/0/+Mobirise\" target=\"_blank\">\n"
                    + "                                <span class=\"socicon-googleplus socicon mbr-iconfont mbr-iconfont-social\"></span>\n"
                    + "                            </a>\n"
                    + "                        </div>\n"
                    + "                        <div class=\"soc-item\">\n"
                    + "                            <a href=\"https://www.behance.net/Mobirise\" target=\"_blank\">\n"
                    + "                                <span class=\"socicon-behance socicon mbr-iconfont mbr-iconfont-social\"></span>\n"
                    + "                            </a>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div>\n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "</section>\n"
                    + "\n"
                    + "\n"
                    + "  <script src=\"assets/web/assets/jquery/jquery.min.js\"></script>\n"
                    + "  <script src=\"assets/popper/popper.min.js\"></script>\n"
                    + "  <script src=\"assets/tether/tether.min.js\"></script>\n"
                    + "  <script src=\"assets/bootstrap/js/bootstrap.min.js\"></script>\n"
                    + "  <script src=\"assets/smoothscroll/smooth-scroll.js\"></script>\n"
                    + "  <script src=\"assets/parallax/jarallax.min.js\"></script>\n"
                    + "  <script src=\"assets/viewportchecker/jquery.viewportchecker.js\"></script>\n"
                    + "  <script src=\"assets/masonry/masonry.pkgd.min.js\"></script>\n"
                    + "  <script src=\"assets/imagesloaded/imagesloaded.pkgd.min.js\"></script>\n"
                    + "  <script src=\"assets/touchswipe/jquery.touch-swipe.min.js\"></script>\n"
                    + "  <script src=\"assets/vimeoplayer/jquery.mb.vimeo_player.js\"></script>\n"
                    + "  <script src=\"assets/dropdown/js/script.min.js\"></script>\n"
                    + "  <script src=\"assets/mbr-clients-slider/mbr-clients-slider.js\"></script>\n"
                    + "  <script src=\"assets/bootstrapcarouselswipe/bootstrap-carousel-swipe.js\"></script>\n"
                    + "  <script src=\"assets/theme/js/script.js\"></script>\n"
                    + "  <script src=\"assets/slidervideo/script.js\"></script>\n"
                    + "  <script src=\"assets/gallery/player.min.js\"></script>\n"
                    + "  <script src=\"assets/gallery/script.js\"></script>\n"
                    + "  <script src=\"assets/formoid/formoid.min.js\"></script>\n"
                    + "  \n"
                    + "  \n"
                    + " <div id=\"scrollToTop\" class=\"scrollToTop mbr-arrow-up\"><a style=\"text-align: center;\"><i></i></a></div>\n"
                    + "    <input name=\"animation\" type=\"hidden\">\n"
                    + "  </body>\n"
                    + "</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
